# Generated by Django 2.2.6 on 2020-02-03 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('numFavors', models.IntegerField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=256)),
                ('isEvent', models.BooleanField(default=False)),
                ('requesterSigned', models.BooleanField(default=False)),
                ('giverSigned', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
