# Generated by Django 3.0.1 on 2020-02-16 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favor',
            old_name='giverSigned',
            new_name='giver_signed',
        ),
        migrations.RenameField(
            model_name='favor',
            old_name='numFavors',
            new_name='number_of_favors',
        ),
        migrations.RenameField(
            model_name='favor',
            old_name='isEvent',
            new_name='requester_signed',
        ),
        migrations.RenameField(
            model_name='favor',
            old_name='requesterSigned',
            new_name='volunteer_event',
        ),
        migrations.RemoveField(
            model_name='favor',
            name='started',
        ),
    ]
