# Generated by Django 3.0.1 on 2020-02-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorApp', '0002_auto_20200216_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favor',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
