# Generated by Django 3.0.1 on 2020-03-01 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorApp', '0003_auto_20200216_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='favor',
            name='pendingUsers',
            field=models.ManyToManyField(related_name='pending_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
