# Generated by Django 3.0.1 on 2020-03-02 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorApp', '0004_favor_pendingusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favor',
            name='pendingUsers',
        ),
    ]
