# Generated by Django 3.0.1 on 2020-03-09 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorApp', '0006_favor_pendingusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favor',
            name='giver_signed',
        ),
        migrations.RemoveField(
            model_name='favor',
            name='requester_signed',
        ),
        migrations.RemoveField(
            model_name='favor',
            name='volunteer_event',
        ),
    ]
