# Generated by Django 2.1.5 on 2020-03-09 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorApp', '0007_auto_20200309_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='favor',
            name='confirmedUsers',
            field=models.ManyToManyField(related_name='confirmed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
